# Generated by Django 5.2 on 2025-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
