# Generated by Django 5.2 on 2025-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_profile_gender_profile_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="language",
        ),
        migrations.AddField(
            model_name="profile",
            name="minor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
